config/routes.rb
Rails.application.routes.draw do
  root to: 'cocktails#index'
  resources :doses, only: [:destroy, :edit, :update]
  resources :cocktails, except: :index do
    resources :doses, only: [:new, :create]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses

  validates :name, presence: true, uniqueness: true

end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :description, presence: true
  validates :cocktail, uniqueness: { scope: :ingredient }

end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  has_many :cocktail, through: :doses

  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only: [:show, :edit, :update, :destroy]

  def index
    @cocktails = Cocktail.all
  end

  def show
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to @cocktail, notice: 'Cocktail was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @cocktail.update(cocktail_params)
      redirect_to @cocktail, notice: 'Cocktail was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @cocktail.destroy
    redirect_to root_path, notice: 'Cocktail was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  def set_cocktail
      @cocktail = Cocktail.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
  def cocktail_params
      params.require(:cocktail).permit(:name)
    end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :set_dose, only: [:edit, :update, :destroy]
  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
    @dose.cocktail = @cocktail
  end

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    ingredients = params[:dose][:ingredient]
    ingredients.each do |ingredient|
      @dose = Dose.new(dose_params)
      @dose.ingredient = Ingredient.find(ingredient)
      @dose.cocktail = @cocktail
      @dose.save
    end
    redirect_to @cocktail
  end

  def edit
  end

  def update
    if @dose.update(dose_params)
      redirect_to @dose.cocktail, notice: 'Dose was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @cocktail = @dose.cocktail
    @dose.destroy
    redirect_to @cocktail, notice: 'Dose was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  def set_dose
      @dose = Dose.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
  def dose_params
      params.require(:dose).permit(:description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/_form.html.erb
<%= simple_form_for(@cocktail) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions btn btn-success mb-2 p-0">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/cocktails/edit.html.erb
<h1>Edit Cocktail</h1>
<%= render 'form', cocktaill: @cocktail %>
<%= link_to 'Show', @cocktail, class: "text-dark"%> |
<%= link_to 'Back', root_path, class: "text-dark"%>

app/views/cocktails/index.html.erb
<div class="cards">
  <% @cocktails.each do |cocktail| %>
    <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/breakfast.jpg)">
      <%= link_to cocktail.name, cocktail_path(cocktail) %>
      <div class="card-tags">
        <% cocktail.ingredients.each do |ingredient| %>
          <span><%= ingredient.name %></span>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/cocktails/new.html.erb
<h1>New Cocktail</h1>
<%= render 'form', cocktaill: @cocktail %>
<%= link_to 'Back', root_path, class: "btn btn-dark"%>

app/views/cocktails/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/background.png);">
  <div class="container h-100 ">

    <h1 class="d-inline-flex"><%= @cocktail.name %></h1>
    <div class="d-inline-flex">
      <%= link_to cocktail_path(@cocktail), method: :delete, data: { confirm: 'Are you sure?' },class: "mx-3" do %>
        <i class="fas fa-trash"></i>
      <% end %>
      <%= link_to edit_cocktail_path(@cocktail) do %>
        <i class="far fa-edit"></i>
      <% end %>
    </div>
    <% @cocktail.doses.each do |dose| %>
      <p class="mb-0"><%= "#{dose.description}  #{dose.ingredient.name}  "%><%= link_to edit_dose_path(dose) do %>
          <i class="fas fa-pencil-alt"></i>
        <% end %>
        <%= link_to dose_path(dose), method: :delete do %>
          <i class="fas fa-trash"></i>
        <% end %>
      </p>
    <% end %>
    <%= link_to "New dose", new_cocktail_dose_path(@cocktail), class: "btn btn-primary" %>
  </div>
</div>

app/views/doses/_form.html.erb
<%= simple_form_for [@cocktail, @dose] do |form| %>
  <%= form.input :description %>
  <%= form.input :ingredient, collection: Ingredient.all.order(:name), input_html: { multiple: true, class: 'select2'}, include_hidden: false %>
  <div class="form-actions btn btn-success mb-2 p-0">
    <%= form.button :submit %>
  </div>
<% end %>

app/views/doses/destroy.html.erb
<h1>Doses#destroy</h1>
<p>Find me in app/views/doses/destroy.html.erb</p>

app/views/doses/edit.html.erb
<h1>Doses#edit</h1>
<%= render 'form',  dose: @dose, cocktaill: @dose.cocktail %>
<%= link_to 'Show', @dose.cocktail, class: "text-dark" %> |
<%= link_to 'Back', root_path, class: "text-dark" %>

app/views/doses/new.html.erb
<h1>Doses#new</h1>
<%= render 'form', dose: @dose, cocktaill: @dose.cocktail %>
<%= link_to 'Show', @dose.cocktail, class: "text-dark" %> |
<%= link_to 'Back', root_path, class: "text-dark" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag    'application', media: 'all'%>
  </head>

  <body>
    <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
      <%= link_to "Cocktails", root_path, class: "navbar-brand"  %>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>


      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <%= link_to "New Cocktail", new_cocktail_path, class: "nav-link" %>
          </li>
        </ul>
      </div>
    </div>

    <div class="container mt-3">
    <%= yield %>
    </div>
    <%= javascript_include_tag 'application'%>
    <%= javascript_pack_tag "application" %>
  </body>
</html>